### PR TITLE
fix get dual indexing error

### PR DESCRIPTION
**Pull request by thisiscam**
This attempts to fix an indexing error when using the simplex method to solve LP.

I believe that this should apply to the interior point method as well.

Lastly, I think this also need to take care of the equality constraints somehow? I'm not sure if the current behavior considers that.

### CODE REVIEW

**Comment by mckib2** [comment]
@thisiscam Thanks for spotting this!  It looks good to me, do you want to make the change for the interor point method as well?  Might as well get them both at once

**Comment by thisiscam** [comment]
Do you think the equality constraint is handled correctly right now? 
I'm not sure how to fix that (if it's buggy).

**Comment by mckib2** [comment]
Equality constraints are set [here](https://github.com/mckib2/scikit-glpk/blob/aa67ba4a5373cb7ccf439623958655f3e75e822c/glpk/_utils.py#L94) if I understand what you're talking about correctly.  If this is not the correct behavior, please open up another issue and we can take a look at.  A reproducing example would be good to show the undesired behavior if there is any.

As far as this PR goes, I think it looks good so I'll go ahead and merge it.  Thanks @thisiscam !

**Comment by thisiscam** [comment]
@mckib2  Thanks for merging!

My concern is regarding this line https://github.com/psg-mit/scikit-glpk/blob/4a93aa352822728420dfb77af186de0daba5a20a/glpk/_glpk.py#L370. 

Currently it only refers to `b_ub`, should it also somehow use `b_eq`? I'm not really familiar with how the dual is computed, so the answer could  totally be that this is ok.

**Comment by mckib2** [comment]
I believe duals only arise from upper bound constraints, I'll look it up and get back to you

__EDIT__: This is incorrect, there should be a dual for all constraints including equality, I'll fix this real quick

**Pull request merged**
